android.useAndroidX=true
org.gradle.daemon=true
android.enableR8=true
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true

# 16KB Page Size Support (Required for Google Play by Nov 1, 2025)
android.experimental.enable16KbPageSize=true